/**
 * Seed UFC Fighter Stats Data
 *
 * Populates the UFC reference tables with realistic fighter data
 * for development and testing purposes.
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.0';

const supabaseUrl = Deno.env.get('SUPABASE_URL');
const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

if (!supabaseUrl || !serviceRoleKey) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
  Deno.exit(1);
}

const supabase = createClient(supabaseUrl, serviceRoleKey);

// Snapshot ID for this seed data
const SNAPSHOT_ID = 'seed_20260107_dev';

// Sample UFC fighters with realistic stats
const FIGHTERS = [
  {
    fighter_id: 'islam_makhachev_001',
    first_name: 'Islam',
    last_name: 'Makhachev',
    full_name: 'Islam Makhachev',
    nickname: null,
    dob: '1991-10-27',
    height_inches: 70,
    weight_lbs: 155,
    reach_inches: 70,
    stance: 'Southpaw',
    record_wins: 26,
    record_losses: 1,
    record_draws: 0,
    record_nc: 0,
    slpm: 2.85,
    sapm: 1.47,
    str_acc: 59,
    str_def: 65,
    td_avg: 3.21,
    td_acc: 61,
    td_def: 91,
    sub_avg: 1.2,
  },
  {
    fighter_id: 'alex_pereira_002',
    first_name: 'Alex',
    last_name: 'Pereira',
    full_name: 'Alex Pereira',
    nickname: 'Poatan',
    dob: '1987-07-07',
    height_inches: 76,
    weight_lbs: 205,
    reach_inches: 79,
    stance: 'Orthodox',
    record_wins: 12,
    record_losses: 2,
    record_draws: 0,
    record_nc: 0,
    slpm: 5.62,
    sapm: 4.01,
    str_acc: 56,
    str_def: 54,
    td_avg: 0.0,
    td_acc: 0,
    td_def: 92,
    sub_avg: 0.0,
  },
  {
    fighter_id: 'jon_jones_003',
    first_name: 'Jon',
    last_name: 'Jones',
    full_name: 'Jon Jones',
    nickname: 'Bones',
    dob: '1987-07-19',
    height_inches: 76,
    weight_lbs: 248,
    reach_inches: 84,
    stance: 'Orthodox',
    record_wins: 27,
    record_losses: 1,
    record_draws: 0,
    record_nc: 1,
    slpm: 4.35,
    sapm: 2.18,
    str_acc: 57,
    str_def: 64,
    td_avg: 1.91,
    td_acc: 44,
    td_def: 95,
    sub_avg: 0.5,
  },
  {
    fighter_id: 'leon_edwards_004',
    first_name: 'Leon',
    last_name: 'Edwards',
    full_name: 'Leon Edwards',
    nickname: 'Rocky',
    dob: '1991-08-25',
    height_inches: 72,
    weight_lbs: 170,
    reach_inches: 74,
    stance: 'Southpaw',
    record_wins: 22,
    record_losses: 3,
    record_draws: 0,
    record_nc: 1,
    slpm: 3.85,
    sapm: 2.75,
    str_acc: 48,
    str_def: 60,
    td_avg: 1.52,
    td_acc: 44,
    td_def: 82,
    sub_avg: 0.3,
  },
  {
    fighter_id: 'sean_omalley_005',
    first_name: 'Sean',
    last_name: "O'Malley",
    full_name: "Sean O'Malley",
    nickname: 'Suga',
    dob: '1994-10-24',
    height_inches: 71,
    weight_lbs: 135,
    reach_inches: 72,
    stance: 'Southpaw',
    record_wins: 18,
    record_losses: 1,
    record_draws: 0,
    record_nc: 1,
    slpm: 5.61,
    sapm: 3.14,
    str_acc: 52,
    str_def: 56,
    td_avg: 0.15,
    td_acc: 28,
    td_def: 65,
    sub_avg: 0.0,
  },
  {
    fighter_id: 'ilia_topuria_006',
    first_name: 'Ilia',
    last_name: 'Topuria',
    full_name: 'Ilia Topuria',
    nickname: 'El Matador',
    dob: '1997-01-21',
    height_inches: 67,
    weight_lbs: 145,
    reach_inches: 69,
    stance: 'Orthodox',
    record_wins: 16,
    record_losses: 0,
    record_draws: 0,
    record_nc: 0,
    slpm: 5.93,
    sapm: 3.42,
    str_acc: 50,
    str_def: 62,
    td_avg: 1.85,
    td_acc: 52,
    td_def: 88,
    sub_avg: 1.0,
  },
  {
    fighter_id: 'dricus_duplessis_007',
    first_name: 'Dricus',
    last_name: 'Du Plessis',
    full_name: 'Dricus Du Plessis',
    nickname: 'Stillknocks',
    dob: '1994-01-14',
    height_inches: 72,
    weight_lbs: 185,
    reach_inches: 76,
    stance: 'Orthodox',
    record_wins: 22,
    record_losses: 2,
    record_draws: 0,
    record_nc: 0,
    slpm: 7.02,
    sapm: 4.35,
    str_acc: 50,
    str_def: 50,
    td_avg: 2.21,
    td_acc: 37,
    td_def: 62,
    sub_avg: 0.4,
  },
  {
    fighter_id: 'merab_dvalishvili_008',
    first_name: 'Merab',
    last_name: 'Dvalishvili',
    full_name: 'Merab Dvalishvili',
    nickname: 'The Machine',
    dob: '1991-03-09',
    height_inches: 67,
    weight_lbs: 135,
    reach_inches: 66,
    stance: 'Orthodox',
    record_wins: 18,
    record_losses: 4,
    record_draws: 0,
    record_nc: 0,
    slpm: 4.52,
    sapm: 4.15,
    str_acc: 43,
    str_def: 53,
    td_avg: 7.68,
    td_acc: 40,
    td_def: 71,
    sub_avg: 0.2,
  },
  {
    fighter_id: 'charles_oliveira_009',
    first_name: 'Charles',
    last_name: 'Oliveira',
    full_name: 'Charles Oliveira',
    nickname: 'Do Bronx',
    dob: '1989-10-17',
    height_inches: 70,
    weight_lbs: 155,
    reach_inches: 74,
    stance: 'Orthodox',
    record_wins: 34,
    record_losses: 10,
    record_draws: 0,
    record_nc: 1,
    slpm: 3.48,
    sapm: 3.32,
    str_acc: 53,
    str_def: 54,
    td_avg: 2.52,
    td_acc: 42,
    td_def: 52,
    sub_avg: 2.1,
  },
  {
    fighter_id: 'belal_muhammad_010',
    first_name: 'Belal',
    last_name: 'Muhammad',
    full_name: 'Belal Muhammad',
    nickname: 'Remember The Name',
    dob: '1988-06-03',
    height_inches: 71,
    weight_lbs: 170,
    reach_inches: 72,
    stance: 'Southpaw',
    record_wins: 24,
    record_losses: 3,
    record_draws: 0,
    record_nc: 1,
    slpm: 4.13,
    sapm: 2.93,
    str_acc: 43,
    str_def: 56,
    td_avg: 4.22,
    td_acc: 36,
    td_def: 75,
    sub_avg: 0.1,
  },
  {
    fighter_id: 'max_holloway_011',
    first_name: 'Max',
    last_name: 'Holloway',
    full_name: 'Max Holloway',
    nickname: 'Blessed',
    dob: '1991-12-04',
    height_inches: 71,
    weight_lbs: 145,
    reach_inches: 69,
    stance: 'Orthodox',
    record_wins: 26,
    record_losses: 7,
    record_draws: 0,
    record_nc: 0,
    slpm: 7.09,
    sapm: 4.35,
    str_acc: 46,
    str_def: 56,
    td_avg: 0.32,
    td_acc: 50,
    td_def: 85,
    sub_avg: 0.1,
  },
  {
    fighter_id: 'valentina_shevchenko_012',
    first_name: 'Valentina',
    last_name: 'Shevchenko',
    full_name: 'Valentina Shevchenko',
    nickname: 'Bullet',
    dob: '1988-03-07',
    height_inches: 65,
    weight_lbs: 125,
    reach_inches: 67,
    stance: 'Southpaw',
    record_wins: 23,
    record_losses: 4,
    record_draws: 1,
    record_nc: 0,
    slpm: 4.54,
    sapm: 2.82,
    str_acc: 48,
    str_def: 68,
    td_avg: 1.87,
    td_acc: 35,
    td_def: 97,
    sub_avg: 0.5,
  },
  {
    fighter_id: 'zhang_weili_013',
    first_name: 'Zhang',
    last_name: 'Weili',
    full_name: 'Zhang Weili',
    nickname: 'Magnum',
    dob: '1989-08-13',
    height_inches: 64,
    weight_lbs: 115,
    reach_inches: 63,
    stance: 'Orthodox',
    record_wins: 25,
    record_losses: 3,
    record_draws: 0,
    record_nc: 0,
    slpm: 6.35,
    sapm: 3.89,
    str_acc: 45,
    str_def: 60,
    td_avg: 2.15,
    td_acc: 48,
    td_def: 73,
    sub_avg: 0.3,
  },
  {
    fighter_id: 'tom_aspinall_014',
    first_name: 'Tom',
    last_name: 'Aspinall',
    full_name: 'Tom Aspinall',
    nickname: null,
    dob: '1993-04-11',
    height_inches: 77,
    weight_lbs: 252,
    reach_inches: 78,
    stance: 'Orthodox',
    record_wins: 15,
    record_losses: 3,
    record_draws: 0,
    record_nc: 0,
    slpm: 6.24,
    sapm: 2.47,
    str_acc: 60,
    str_def: 51,
    td_avg: 1.78,
    td_acc: 46,
    td_def: 81,
    sub_avg: 1.4,
  },
  {
    fighter_id: 'ciryl_gane_015',
    first_name: 'Ciryl',
    last_name: 'Gane',
    full_name: 'Ciryl Gane',
    nickname: 'Bon Gamin',
    dob: '1990-04-12',
    height_inches: 77,
    weight_lbs: 247,
    reach_inches: 81,
    stance: 'Orthodox',
    record_wins: 12,
    record_losses: 2,
    record_draws: 0,
    record_nc: 0,
    slpm: 4.93,
    sapm: 2.92,
    str_acc: 59,
    str_def: 61,
    td_avg: 0.61,
    td_acc: 71,
    td_def: 68,
    sub_avg: 0.4,
  },
  {
    fighter_id: 'alexander_volkanovski_016',
    first_name: 'Alexander',
    last_name: 'Volkanovski',
    full_name: 'Alexander Volkanovski',
    nickname: 'The Great',
    dob: '1988-09-29',
    height_inches: 66,
    weight_lbs: 145,
    reach_inches: 71,
    stance: 'Orthodox',
    record_wins: 26,
    record_losses: 4,
    record_draws: 0,
    record_nc: 0,
    slpm: 6.58,
    sapm: 4.04,
    str_acc: 57,
    str_def: 60,
    td_avg: 2.57,
    td_acc: 48,
    td_def: 77,
    sub_avg: 0.0,
  },
  {
    fighter_id: 'dustin_poirier_017',
    first_name: 'Dustin',
    last_name: 'Poirier',
    full_name: 'Dustin Poirier',
    nickname: 'The Diamond',
    dob: '1989-01-19',
    height_inches: 69,
    weight_lbs: 155,
    reach_inches: 72,
    stance: 'Southpaw',
    record_wins: 30,
    record_losses: 9,
    record_draws: 0,
    record_nc: 1,
    slpm: 5.53,
    sapm: 4.52,
    str_acc: 52,
    str_def: 54,
    td_avg: 1.12,
    td_acc: 52,
    td_def: 69,
    sub_avg: 1.2,
  },
  {
    fighter_id: 'conor_mcgregor_018',
    first_name: 'Conor',
    last_name: 'McGregor',
    full_name: 'Conor McGregor',
    nickname: 'Notorious',
    dob: '1988-07-14',
    height_inches: 69,
    weight_lbs: 155,
    reach_inches: 74,
    stance: 'Southpaw',
    record_wins: 22,
    record_losses: 6,
    record_draws: 0,
    record_nc: 0,
    slpm: 5.32,
    sapm: 4.41,
    str_acc: 49,
    str_def: 51,
    td_avg: 0.74,
    td_acc: 57,
    td_def: 63,
    sub_avg: 0.3,
  },
  {
    fighter_id: 'khamzat_chimaev_019',
    first_name: 'Khamzat',
    last_name: 'Chimaev',
    full_name: 'Khamzat Chimaev',
    nickname: 'Borz',
    dob: '1994-05-01',
    height_inches: 74,
    weight_lbs: 185,
    reach_inches: 75,
    stance: 'Orthodox',
    record_wins: 13,
    record_losses: 0,
    record_draws: 0,
    record_nc: 0,
    slpm: 4.54,
    sapm: 1.47,
    str_acc: 58,
    str_def: 73,
    td_avg: 3.41,
    td_acc: 60,
    td_def: 100,
    sub_avg: 0.9,
  },
  {
    fighter_id: 'amanda_nunes_020',
    first_name: 'Amanda',
    last_name: 'Nunes',
    full_name: 'Amanda Nunes',
    nickname: 'The Lioness',
    dob: '1988-05-30',
    height_inches: 68,
    weight_lbs: 135,
    reach_inches: 69,
    stance: 'Orthodox',
    record_wins: 23,
    record_losses: 5,
    record_draws: 0,
    record_nc: 0,
    slpm: 5.04,
    sapm: 3.63,
    str_acc: 48,
    str_def: 60,
    td_avg: 1.88,
    td_acc: 53,
    td_def: 78,
    sub_avg: 0.8,
  },
];

// Sample events for fight history
const EVENTS = [
  {
    event_id: 'event_ufc_309',
    name: 'UFC 309: Jones vs. Miocic',
    event_date: '2024-11-16',
    location: 'New York City, New York',
  },
  {
    event_id: 'event_ufc_308',
    name: 'UFC 308: Topuria vs. Holloway',
    event_date: '2024-10-26',
    location: 'Abu Dhabi, UAE',
  },
  {
    event_id: 'event_ufc_307',
    name: 'UFC 307: Pereira vs. Rountree',
    event_date: '2024-10-05',
    location: 'Salt Lake City, Utah',
  },
  {
    event_id: 'event_ufc_306',
    name: 'UFC 306: O\'Malley vs. Dvalishvili',
    event_date: '2024-09-14',
    location: 'Las Vegas, Nevada',
  },
  {
    event_id: 'event_ufc_305',
    name: 'UFC 305: Du Plessis vs. Adesanya',
    event_date: '2024-08-17',
    location: 'Perth, Australia',
  },
  {
    event_id: 'event_ufc_304',
    name: 'UFC 304: Edwards vs. Muhammad 2',
    event_date: '2024-07-27',
    location: 'Manchester, England',
  },
  {
    event_id: 'event_ufc_303',
    name: 'UFC 303: Pereira vs. Prochazka 2',
    event_date: '2024-06-29',
    location: 'Las Vegas, Nevada',
  },
  {
    event_id: 'event_ufc_302',
    name: 'UFC 302: Makhachev vs. Poirier',
    event_date: '2024-06-01',
    location: 'Newark, New Jersey',
  },
  {
    event_id: 'event_ufc_300',
    name: 'UFC 300: Pereira vs. Hill',
    event_date: '2024-04-13',
    location: 'Las Vegas, Nevada',
  },
  {
    event_id: 'event_ufc_298',
    name: 'UFC 298: Volkanovski vs. Topuria',
    event_date: '2024-02-17',
    location: 'Anaheim, California',
  },
];

// Sample fights with results
const FIGHTS = [
  // Islam Makhachev fights
  {
    fight_id: 'fight_001',
    event_id: 'event_ufc_302',
    bout_order: 1,
    weight_class: 'Lightweight',
    is_title_fight: true,
    scheduled_rounds: 5,
    red_fighter_id: 'islam_makhachev_001',
    blue_fighter_id: 'dustin_poirier_017',
    red_fighter_name: 'Islam Makhachev',
    blue_fighter_name: 'Dustin Poirier',
    winner_fighter_id: 'islam_makhachev_001',
    loser_fighter_id: 'dustin_poirier_017',
    result_method: 'Submission',
    result_method_details: 'D\'Arce Choke',
    result_round: 5,
    result_time_seconds: 244,
    referee: 'Jason Herzog',
  },
  // Alex Pereira fights
  {
    fight_id: 'fight_002',
    event_id: 'event_ufc_307',
    bout_order: 1,
    weight_class: 'Light Heavyweight',
    is_title_fight: true,
    scheduled_rounds: 5,
    red_fighter_id: 'alex_pereira_002',
    blue_fighter_id: null,
    red_fighter_name: 'Alex Pereira',
    blue_fighter_name: 'Khalil Rountree Jr.',
    winner_fighter_id: 'alex_pereira_002',
    loser_fighter_id: null,
    result_method: 'TKO',
    result_method_details: 'Punches',
    result_round: 4,
    result_time_seconds: 255,
    referee: 'Marc Goddard',
  },
  {
    fight_id: 'fight_003',
    event_id: 'event_ufc_303',
    bout_order: 1,
    weight_class: 'Light Heavyweight',
    is_title_fight: true,
    scheduled_rounds: 5,
    red_fighter_id: 'alex_pereira_002',
    blue_fighter_id: null,
    red_fighter_name: 'Alex Pereira',
    blue_fighter_name: 'Jiri Prochazka',
    winner_fighter_id: 'alex_pereira_002',
    loser_fighter_id: null,
    result_method: 'KO',
    result_method_details: 'Head Kick',
    result_round: 2,
    result_time_seconds: 13,
    referee: 'Herb Dean',
  },
  {
    fight_id: 'fight_004',
    event_id: 'event_ufc_300',
    bout_order: 1,
    weight_class: 'Light Heavyweight',
    is_title_fight: true,
    scheduled_rounds: 5,
    red_fighter_id: 'alex_pereira_002',
    blue_fighter_id: null,
    red_fighter_name: 'Alex Pereira',
    blue_fighter_name: 'Jamahal Hill',
    winner_fighter_id: 'alex_pereira_002',
    loser_fighter_id: null,
    result_method: 'KO',
    result_method_details: 'Punches',
    result_round: 1,
    result_time_seconds: 117,
    referee: 'Herb Dean',
  },
  // Ilia Topuria fights
  {
    fight_id: 'fight_005',
    event_id: 'event_ufc_308',
    bout_order: 1,
    weight_class: 'Featherweight',
    is_title_fight: true,
    scheduled_rounds: 5,
    red_fighter_id: 'ilia_topuria_006',
    blue_fighter_id: 'max_holloway_011',
    red_fighter_name: 'Ilia Topuria',
    blue_fighter_name: 'Max Holloway',
    winner_fighter_id: 'ilia_topuria_006',
    loser_fighter_id: 'max_holloway_011',
    result_method: 'KO',
    result_method_details: 'Punches',
    result_round: 3,
    result_time_seconds: 152,
    referee: 'Marc Goddard',
  },
  {
    fight_id: 'fight_006',
    event_id: 'event_ufc_298',
    bout_order: 1,
    weight_class: 'Featherweight',
    is_title_fight: true,
    scheduled_rounds: 5,
    red_fighter_id: 'alexander_volkanovski_016',
    blue_fighter_id: 'ilia_topuria_006',
    red_fighter_name: 'Alexander Volkanovski',
    blue_fighter_name: 'Ilia Topuria',
    winner_fighter_id: 'ilia_topuria_006',
    loser_fighter_id: 'alexander_volkanovski_016',
    result_method: 'KO',
    result_method_details: 'Punches',
    result_round: 2,
    result_time_seconds: 174,
    referee: 'Jason Herzog',
  },
  // Leon Edwards fights
  {
    fight_id: 'fight_007',
    event_id: 'event_ufc_304',
    bout_order: 1,
    weight_class: 'Welterweight',
    is_title_fight: true,
    scheduled_rounds: 5,
    red_fighter_id: 'leon_edwards_004',
    blue_fighter_id: 'belal_muhammad_010',
    red_fighter_name: 'Leon Edwards',
    blue_fighter_name: 'Belal Muhammad',
    winner_fighter_id: 'belal_muhammad_010',
    loser_fighter_id: 'leon_edwards_004',
    result_method: 'Decision',
    result_method_details: 'Unanimous',
    result_round: 5,
    result_time_seconds: 300,
    referee: 'Marc Goddard',
  },
  // Sean O'Malley fights
  {
    fight_id: 'fight_008',
    event_id: 'event_ufc_306',
    bout_order: 1,
    weight_class: 'Bantamweight',
    is_title_fight: true,
    scheduled_rounds: 5,
    red_fighter_id: 'sean_omalley_005',
    blue_fighter_id: 'merab_dvalishvili_008',
    red_fighter_name: "Sean O'Malley",
    blue_fighter_name: 'Merab Dvalishvili',
    winner_fighter_id: 'merab_dvalishvili_008',
    loser_fighter_id: 'sean_omalley_005',
    result_method: 'Decision',
    result_method_details: 'Unanimous',
    result_round: 5,
    result_time_seconds: 300,
    referee: 'Herb Dean',
  },
  // Dricus Du Plessis fights
  {
    fight_id: 'fight_009',
    event_id: 'event_ufc_305',
    bout_order: 1,
    weight_class: 'Middleweight',
    is_title_fight: true,
    scheduled_rounds: 5,
    red_fighter_id: 'dricus_duplessis_007',
    blue_fighter_id: null,
    red_fighter_name: 'Dricus Du Plessis',
    blue_fighter_name: 'Israel Adesanya',
    winner_fighter_id: 'dricus_duplessis_007',
    loser_fighter_id: null,
    result_method: 'Submission',
    result_method_details: 'Rear-Naked Choke',
    result_round: 4,
    result_time_seconds: 246,
    referee: 'Marc Goddard',
  },
  // Max Holloway earlier fight
  {
    fight_id: 'fight_010',
    event_id: 'event_ufc_300',
    bout_order: 2,
    weight_class: 'Lightweight',
    is_title_fight: false,
    scheduled_rounds: 5,
    red_fighter_id: null,
    blue_fighter_id: 'max_holloway_011',
    red_fighter_name: 'Justin Gaethje',
    blue_fighter_name: 'Max Holloway',
    winner_fighter_id: 'max_holloway_011',
    loser_fighter_id: null,
    result_method: 'KO',
    result_method_details: 'Punch',
    result_round: 5,
    result_time_seconds: 299,
    referee: 'Herb Dean',
  },
];

// Sample fight stats (totals for each fighter in each fight)
const FIGHT_STATS = [
  // Islam vs Poirier - Islam stats
  {
    id: 'stats_001_islam',
    fight_id: 'fight_001',
    fighter_id: 'islam_makhachev_001',
    opponent_id: 'dustin_poirier_017',
    round: null,
    is_total: true,
    knockdowns: 1,
    sig_str_landed: 71,
    sig_str_attempted: 134,
    total_str_landed: 128,
    total_str_attempted: 191,
    td_landed: 5,
    td_attempted: 12,
    sub_attempts: 3,
    reversals: 0,
    ctrl_time_seconds: 721,
  },
  // Islam vs Poirier - Poirier stats
  {
    id: 'stats_001_dustin',
    fight_id: 'fight_001',
    fighter_id: 'dustin_poirier_017',
    opponent_id: 'islam_makhachev_001',
    round: null,
    is_total: true,
    knockdowns: 0,
    sig_str_landed: 44,
    sig_str_attempted: 91,
    total_str_landed: 68,
    total_str_attempted: 111,
    td_landed: 0,
    td_attempted: 2,
    sub_attempts: 0,
    reversals: 1,
    ctrl_time_seconds: 45,
  },
  // Pereira vs Rountree - Pereira stats
  {
    id: 'stats_002_pereira',
    fight_id: 'fight_002',
    fighter_id: 'alex_pereira_002',
    opponent_id: null,
    round: null,
    is_total: true,
    knockdowns: 2,
    sig_str_landed: 106,
    sig_str_attempted: 175,
    total_str_landed: 122,
    total_str_attempted: 198,
    td_landed: 0,
    td_attempted: 0,
    sub_attempts: 0,
    reversals: 0,
    ctrl_time_seconds: 0,
  },
  // Topuria vs Holloway - Topuria stats
  {
    id: 'stats_005_topuria',
    fight_id: 'fight_005',
    fighter_id: 'ilia_topuria_006',
    opponent_id: 'max_holloway_011',
    round: null,
    is_total: true,
    knockdowns: 2,
    sig_str_landed: 68,
    sig_str_attempted: 141,
    total_str_landed: 84,
    total_str_attempted: 165,
    td_landed: 1,
    td_attempted: 3,
    sub_attempts: 0,
    reversals: 0,
    ctrl_time_seconds: 67,
  },
  // Topuria vs Holloway - Holloway stats
  {
    id: 'stats_005_holloway',
    fight_id: 'fight_005',
    fighter_id: 'max_holloway_011',
    opponent_id: 'ilia_topuria_006',
    round: null,
    is_total: true,
    knockdowns: 0,
    sig_str_landed: 58,
    sig_str_attempted: 117,
    total_str_landed: 68,
    total_str_attempted: 128,
    td_landed: 0,
    td_attempted: 0,
    sub_attempts: 0,
    reversals: 0,
    ctrl_time_seconds: 0,
  },
  // Edwards vs Muhammad - Edwards stats
  {
    id: 'stats_007_edwards',
    fight_id: 'fight_007',
    fighter_id: 'leon_edwards_004',
    opponent_id: 'belal_muhammad_010',
    round: null,
    is_total: true,
    knockdowns: 0,
    sig_str_landed: 72,
    sig_str_attempted: 153,
    total_str_landed: 89,
    total_str_attempted: 172,
    td_landed: 0,
    td_attempted: 2,
    sub_attempts: 0,
    reversals: 1,
    ctrl_time_seconds: 31,
  },
  // Edwards vs Muhammad - Muhammad stats
  {
    id: 'stats_007_belal',
    fight_id: 'fight_007',
    fighter_id: 'belal_muhammad_010',
    opponent_id: 'leon_edwards_004',
    round: null,
    is_total: true,
    knockdowns: 0,
    sig_str_landed: 81,
    sig_str_attempted: 196,
    total_str_landed: 102,
    total_str_attempted: 229,
    td_landed: 11,
    td_attempted: 19,
    sub_attempts: 0,
    reversals: 0,
    ctrl_time_seconds: 502,
  },
  // O'Malley vs Dvalishvili - O'Malley stats
  {
    id: 'stats_008_omalley',
    fight_id: 'fight_008',
    fighter_id: 'sean_omalley_005',
    opponent_id: 'merab_dvalishvili_008',
    round: null,
    is_total: true,
    knockdowns: 1,
    sig_str_landed: 61,
    sig_str_attempted: 145,
    total_str_landed: 75,
    total_str_attempted: 162,
    td_landed: 0,
    td_attempted: 0,
    sub_attempts: 0,
    reversals: 0,
    ctrl_time_seconds: 0,
  },
  // O'Malley vs Dvalishvili - Dvalishvili stats
  {
    id: 'stats_008_merab',
    fight_id: 'fight_008',
    fighter_id: 'merab_dvalishvili_008',
    opponent_id: 'sean_omalley_005',
    round: null,
    is_total: true,
    knockdowns: 0,
    sig_str_landed: 152,
    sig_str_attempted: 338,
    total_str_landed: 196,
    total_str_attempted: 395,
    td_landed: 11,
    td_attempted: 23,
    sub_attempts: 1,
    reversals: 1,
    ctrl_time_seconds: 583,
  },
];

async function seedData() {
  console.log('Seeding UFC Fighter Stats data...\n');

  // 1. Create snapshot record
  console.log('Creating source snapshot...');
  const { error: snapshotError } = await supabase
    .from('ufc_source_snapshots')
    .upsert({
      snapshot_id: SNAPSHOT_ID,
      source: 'seed_data',
      fetched_at: new Date().toISOString(),
      git_ref: 'seed',
      notes: 'Development seed data for UFC Fighter Stats feature',
      row_counts: {
        fighters: FIGHTERS.length,
        events: EVENTS.length,
        fights: FIGHTS.length,
        fight_stats: FIGHT_STATS.length,
      },
    }, { onConflict: 'snapshot_id' });

  if (snapshotError) {
    console.error('Error creating snapshot:', snapshotError);
    Deno.exit(1);
  }
  console.log('  Created snapshot:', SNAPSHOT_ID);

  // 2. Insert fighters
  console.log('\nInserting fighters...');
  const fightersWithSnapshot = FIGHTERS.map(f => ({
    ...f,
    source_snapshot_id: SNAPSHOT_ID,
  }));

  const { error: fightersError } = await supabase
    .from('ufc_fighters')
    .upsert(fightersWithSnapshot, { onConflict: 'fighter_id' });

  if (fightersError) {
    console.error('Error inserting fighters:', fightersError);
    Deno.exit(1);
  }
  console.log(`  Inserted ${FIGHTERS.length} fighters`);

  // 3. Insert events
  console.log('\nInserting events...');
  const eventsWithSnapshot = EVENTS.map(e => ({
    ...e,
    source_snapshot_id: SNAPSHOT_ID,
  }));

  const { error: eventsError } = await supabase
    .from('ufc_events')
    .upsert(eventsWithSnapshot, { onConflict: 'event_id' });

  if (eventsError) {
    console.error('Error inserting events:', eventsError);
    Deno.exit(1);
  }
  console.log(`  Inserted ${EVENTS.length} events`);

  // 4. Insert fights
  console.log('\nInserting fights...');
  const fightsWithSnapshot = FIGHTS.map(f => ({
    ...f,
    source_snapshot_id: SNAPSHOT_ID,
  }));

  const { error: fightsError } = await supabase
    .from('ufc_fights')
    .upsert(fightsWithSnapshot, { onConflict: 'fight_id' });

  if (fightsError) {
    console.error('Error inserting fights:', fightsError);
    Deno.exit(1);
  }
  console.log(`  Inserted ${FIGHTS.length} fights`);

  // 5. Insert fight stats
  console.log('\nInserting fight stats...');
  const statsWithSnapshot = FIGHT_STATS.map(s => ({
    ...s,
    source_snapshot_id: SNAPSHOT_ID,
  }));

  const { error: statsError } = await supabase
    .from('ufc_fight_stats')
    .upsert(statsWithSnapshot, { onConflict: 'id' });

  if (statsError) {
    console.error('Error inserting fight stats:', statsError);
    Deno.exit(1);
  }
  console.log(`  Inserted ${FIGHT_STATS.length} fight stats records`);

  console.log('\nSeed data complete!');
  console.log(`  - ${FIGHTERS.length} fighters`);
  console.log(`  - ${EVENTS.length} events`);
  console.log(`  - ${FIGHTS.length} fights`);
  console.log(`  - ${FIGHT_STATS.length} fight stats`);
}

// Run the seed
seedData().catch(console.error);
