/**
 * ErrorBoundary Component
 * App-level error boundary with Sentry integration and recovery UI
 * Catches JavaScript errors in child components and displays fallback UI
 */

import React, { useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  SafeAreaView,
  Linking,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import * as Updates from 'expo-updates';
import * as Sentry from '@sentry/react-native';
import { colors, spacing, radius } from '../lib/tokens';

// Fallback colors in case theme isn't available (error during provider setup)
const FALLBACK_COLORS = {
  background: colors.dark.background,
  surface: colors.dark.surface,
  text: colors.dark.text,
  textSecondary: colors.dark.textSecondary,
  accent: colors.dark.accent,
  danger: colors.dark.danger,
  border: colors.dark.border,
};

interface ErrorFallbackProps {
  error: Error | unknown;
  componentStack: string | null;
  eventId: string | null;
  resetError: () => void;
}

function ErrorFallback({ error, componentStack, eventId, resetError }: ErrorFallbackProps): React.ReactElement {
  const handleRestart = useCallback(async () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);

    try {
      // Try to reload the app using expo-updates
      if (!__DEV__ && Updates.reloadAsync) {
        await Updates.reloadAsync();
      } else {
        // In dev, just reset the error boundary
        resetError();
      }
    } catch {
      // If reload fails, at least reset the error boundary
      resetError();
    }
  }, [resetError]);

  const handleReportBug = useCallback(async () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);

    // Create a GitHub issue URL with error details
    const errorObj = error instanceof Error ? error : new Error(String(error));
    const errorMessage = errorObj.message ?? 'Unknown error';
    const errorStack = errorObj.stack?.slice(0, 500) ?? '';

    const issueTitle = encodeURIComponent(`[Crash Report] ${errorMessage.slice(0, 80)}`);
    const issueBody = encodeURIComponent(
      `## Crash Report\n\n` +
      `**Error:** ${errorMessage}\n\n` +
      `**Event ID:** ${eventId ?? 'N/A'}\n\n` +
      `**Stack Trace (partial):**\n\`\`\`\n${errorStack}\n\`\`\`\n\n` +
      `**Steps to reproduce:**\n1. \n\n` +
      `**Device/OS:**\n- \n\n` +
      `---\n*Generated by Upset crash reporter*`
    );

    const githubUrl = `https://github.com/ch3mistocampus/upset/issues/new?title=${issueTitle}&body=${issueBody}&labels=bug,crash`;

    try {
      const canOpen = await Linking.canOpenURL(githubUrl);
      if (canOpen) {
        await Linking.openURL(githubUrl);
      }
    } catch {
      // Silently fail if we can't open the URL
    }
  }, [error, eventId]);

  const handleEmailSupport = useCallback(async () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);

    const errorMessage = error instanceof Error ? error.message : String(error);
    const subject = encodeURIComponent('[Upset] App Crash Report');
    const body = encodeURIComponent(
      `Hi,\n\n` +
      `The app crashed with the following error:\n\n` +
      `Error: ${errorMessage ?? 'Unknown'}\n` +
      `Event ID: ${eventId ?? 'N/A'}\n\n` +
      `Please describe what you were doing when the crash occurred:\n\n`
    );

    const mailtoUrl = `mailto:hello@upsetmma.app?subject=${subject}&body=${body}`;

    try {
      await Linking.openURL(mailtoUrl);
    } catch {
      // Silently fail
    }
  }, [error, eventId]);

  return (
    <SafeAreaView style={styles.safeArea}>
      <View style={styles.container}>
        <View style={styles.card}>
          {/* Error Icon */}
          <View style={styles.iconContainer}>
            <Ionicons name="warning" size={64} color={FALLBACK_COLORS.danger} />
          </View>

          {/* Title */}
          <Text style={styles.title}>Something Went Wrong</Text>

          {/* Description */}
          <Text style={styles.description}>
            The app encountered an unexpected error. We've been notified and are working on a fix.
          </Text>

          {/* Error details (collapsed by default in production) */}
          {__DEV__ && (
            <View style={styles.errorDetails}>
              <Text style={styles.errorLabel}>Error:</Text>
              <Text style={styles.errorText} numberOfLines={3}>
                {error instanceof Error ? error.message : String(error) ?? 'Unknown error'}
              </Text>
              {eventId && (
                <>
                  <Text style={styles.errorLabel}>Event ID:</Text>
                  <Text style={styles.errorText}>{eventId}</Text>
                </>
              )}
            </View>
          )}

          {/* Primary Action - Restart */}
          <TouchableOpacity
            style={styles.primaryButton}
            onPress={handleRestart}
            activeOpacity={0.8}
            accessibilityRole="button"
            accessibilityLabel="Restart app"
          >
            <Ionicons name="refresh" size={20} color="#fff" style={styles.buttonIcon} />
            <Text style={styles.primaryButtonText}>Restart App</Text>
          </TouchableOpacity>

          {/* Secondary Actions */}
          <View style={styles.secondaryActions}>
            <TouchableOpacity
              style={styles.secondaryButton}
              onPress={handleReportBug}
              activeOpacity={0.7}
              accessibilityRole="button"
              accessibilityLabel="Report bug on GitHub"
            >
              <Ionicons name="logo-github" size={18} color={FALLBACK_COLORS.accent} />
              <Text style={styles.secondaryButtonText}>Report Bug</Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={styles.secondaryButton}
              onPress={handleEmailSupport}
              activeOpacity={0.7}
              accessibilityRole="button"
              accessibilityLabel="Email support"
            >
              <Ionicons name="mail-outline" size={18} color={FALLBACK_COLORS.accent} />
              <Text style={styles.secondaryButtonText}>Email Support</Text>
            </TouchableOpacity>
          </View>

          {/* Event ID for reference */}
          {eventId && !__DEV__ && (
            <Text style={styles.eventIdText}>
              Reference: {eventId.slice(0, 8)}
            </Text>
          )}
        </View>
      </View>
    </SafeAreaView>
  );
}

interface AppErrorBoundaryProps {
  children: React.ReactNode;
}

/**
 * App-level error boundary
 * Wraps the entire app to catch unhandled errors and display recovery UI
 */
export function AppErrorBoundary({ children }: AppErrorBoundaryProps): React.ReactElement {
  return (
    <Sentry.ErrorBoundary
      fallback={({ error, componentStack, resetError, eventId }) => (
        <ErrorFallback
          error={error}
          componentStack={componentStack}
          eventId={eventId}
          resetError={resetError}
        />
      )}
      showDialog={false}
    >
      {children}
    </Sentry.ErrorBoundary>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: FALLBACK_COLORS.background,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
    backgroundColor: FALLBACK_COLORS.background,
  },
  card: {
    backgroundColor: FALLBACK_COLORS.surface,
    borderRadius: radius.lg,
    padding: spacing.xxl,
    width: '100%',
    maxWidth: 400,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: FALLBACK_COLORS.border,
  },
  iconContainer: {
    marginBottom: spacing.lg,
    padding: spacing.md,
    backgroundColor: `${FALLBACK_COLORS.danger}20`,
    borderRadius: radius.full,
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: FALLBACK_COLORS.text,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  description: {
    fontSize: 15,
    color: FALLBACK_COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: spacing.xl,
  },
  errorDetails: {
    backgroundColor: `${FALLBACK_COLORS.danger}10`,
    borderRadius: radius.md,
    padding: spacing.md,
    width: '100%',
    marginBottom: spacing.xl,
  },
  errorLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: FALLBACK_COLORS.danger,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  errorText: {
    fontSize: 12,
    color: FALLBACK_COLORS.textSecondary,
    fontFamily: 'monospace',
    marginBottom: spacing.sm,
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: FALLBACK_COLORS.accent,
    borderRadius: radius.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl,
    width: '100%',
    marginBottom: spacing.lg,
  },
  buttonIcon: {
    marginRight: spacing.sm,
  },
  primaryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  secondaryActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: spacing.lg,
    marginBottom: spacing.lg,
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: FALLBACK_COLORS.border,
  },
  secondaryButtonText: {
    fontSize: 14,
    color: FALLBACK_COLORS.accent,
    marginLeft: spacing.xs,
  },
  eventIdText: {
    fontSize: 11,
    color: FALLBACK_COLORS.textSecondary,
    opacity: 0.7,
  },
});
